<#
.SYNOPSIS
    Generates a P2S (Point-to-Site) child certificate.

.DESCRIPTION
    Creates a child certificate signed by a root certificate for Point-to-Site
    VPN client authentication testing.
    
.NOTES
    Author: Azure Policy Testing Framework
    Version: 1.0.0
    Date: 2026-01-06
    Purpose: P2S VPN certificate generation
    Prerequisite: Requires root certificate generated by gen-cert.ps1
#>

$params = @{
       Type = 'Custom'
       Subject = 'CN=P2SChildCert'
       DnsName = 'P2SChildCert'
       KeySpec = 'Signature'
       KeyExportPolicy = 'Exportable'
       KeyLength = 2048
       HashAlgorithm = 'sha256'
       NotAfter = (Get-Date).AddMonths(18)
       CertStoreLocation = 'Cert:\CurrentUser\My'
       Signer = $cert
       TextExtension = @(
        '2.5.29.37={text}1.3.6.1.5.5.7.3.2')
   }
   New-SelfSignedCertificate @params