# Key Vault Compliance Remediation Script
# Generated: 2026-01-06 12:46:56
# Subscription: ab1336c7-687d-4107-b0f6-9649a0458adb
# Scanned: 10 vault(s)
# Issues: 35

<#
.SYNOPSIS
    Remediate 35 Key Vault compliance issue(s)

.DESCRIPTION
    This script was auto-generated by compliance scan.
    Review each command before executing.
    
    Summary by Category:
    - Access Control: 9 issue(s)
    - Configuration: 4 issue(s)
    - Key Lifecycle: 1 issue(s)
    - Monitoring: 10 issue(s)
    - Network Security: 10 issue(s)
    - Secrets Lifecycle: 1 issue(s)

#>

# Set context
Set-AzContext -SubscriptionId 'ab1336c7-687d-4107-b0f6-9649a0458adb'

# ========================================
# Vault: kv-comp-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 4
# ========================================
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-comp-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-comp-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-comp-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent
# Issue: 2 secret(s) without expiration date
# Severity: Medium
# Framework: CIS 8.3, 8.4, MCSB DP-6
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - expiration periods vary by business requirements
# Example: Set 1-year expiration
Update-AzKeyVaultSecret -VaultName 'kv-comp-oizuglif' -Name 'secret-noexpiry-audit' -Expires (Get-Date).AddYears(1) Update-AzKeyVaultSecret -VaultName 'kv-comp-oizuglif' -Name 'secret-noexpiry-deny' -Expires (Get-Date).AddYears(1)
# Issue: 6 key(s) without expiration date
# Severity: Medium
# Framework: MCSB DP-6
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - key rotation schedules vary
# Example: Set 2-year expiration for encryption keys
Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-ecp256-audit' -Expires (Get-Date).AddYears(2) Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-ecp256-deny' -Expires (Get-Date).AddYears(2) Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-noexpiry-audit' -Expires (Get-Date).AddYears(2) Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-noexpiry-deny' -Expires (Get-Date).AddYears(2) Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-rsa1024-audit' -Expires (Get-Date).AddYears(2) Update-AzKeyVaultKey -VaultName 'kv-comp-oizuglif' -Name 'key-rsa1024-deny' -Expires (Get-Date).AddYears(2)

# ========================================
# Vault: kv-sddeny-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 4
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-sddeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-sddeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-sddeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-sddeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-sddeny-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-ppdeny-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 4
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-ppdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-ppdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-ppdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-ppdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-ppdeny-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-rbdeny-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-rbdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-rbdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-rbdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-rbdeny-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-fwdeny-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-fwdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-fwdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-fwdeny-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-fwdeny-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-sdaudit-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 4
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-sdaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-sdaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-sdaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-sdaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-sdaudit-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-ppaudit-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 4
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-ppaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-ppaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-ppaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-ppaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-ppaudit-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-rbaudit-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-rbaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-rbaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-rbaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-rbaudit-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-fwaudit-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-fwaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-fwaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-fwaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-fwaudit-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-plaudit-oizuglif
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-plaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-plaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-plaudit-oizuglif' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-plaudit-oizuglif' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

Write-Host "
Remediation complete. Review results and update compliance dashboard." -ForegroundColor Green
