# Key Vault Compliance Remediation Script
# Generated: 2026-01-06 20:45:01
# Subscription: ab1336c7-687d-4107-b0f6-9649a0458adb
# Scanned: 5 vault(s)
# Issues: 16

<#
.SYNOPSIS
    Remediate 16 Key Vault compliance issue(s)

.DESCRIPTION
    This script was auto-generated by compliance scan.
    Review each command before executing.
    
    Summary by Category:
    - Access Control: 1 issue(s)
    - Configuration: 3 issue(s)
    - Key Lifecycle: 1 issue(s)
    - Monitoring: 5 issue(s)
    - Network Security: 4 issue(s)
    - Secrets Lifecycle: 2 issue(s)

#>

# Set context
Set-AzContext -SubscriptionId 'ab1336c7-687d-4107-b0f6-9649a0458adb'

# ========================================
# Vault: kv-bl-sec-hzxmpoga
# Resource Group: rg-policy-keyvault-test
# Issues: 2
# ========================================
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-sec-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-sec-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-bl-sec-hzxmpoga' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-bl-rbac-hzxmpoga
# Resource Group: rg-policy-keyvault-test
# Issues: 1
# ========================================
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-bl-rbac-hzxmpoga' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

# ========================================
# Vault: kv-bl-leg-hzxmpoga
# Resource Group: rg-policy-keyvault-test
# Issues: 5
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-bl-leg-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: Using legacy access policy model (should migrate to RBAC)
# Severity: Medium
# Framework: CIS 8.6, MCSB PA-7
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - RBAC migration affects access policies
# 1. Document existing access policies
# 2. Plan RBAC role assignments
# 3. Test in non-production first
Update-AzKeyVault -VaultName 'kv-bl-leg-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -EnableRbacAuthorization
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-leg-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-leg-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-bl-leg-hzxmpoga' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent
# Issue: 1 secret(s) without expiration date
# Severity: Medium
# Framework: CIS 8.3, 8.4, MCSB DP-6
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - expiration periods vary by business requirements
# Example: Set 1-year expiration
Update-AzKeyVaultSecret -VaultName 'kv-bl-leg-hzxmpoga' -Name 'LegacySecret' -Expires (Get-Date).AddYears(1)

# ========================================
# Vault: kv-bl-pub-hzxmpoga
# Resource Group: rg-policy-keyvault-test
# Issues: 5
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-bl-pub-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-pub-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-pub-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-bl-pub-hzxmpoga' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent
# Issue: 1 secret(s) without expiration date
# Severity: Medium
# Framework: CIS 8.3, 8.4, MCSB DP-6
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - expiration periods vary by business requirements
# Example: Set 1-year expiration
Update-AzKeyVaultSecret -VaultName 'kv-bl-pub-hzxmpoga' -Name 'PublicSecret' -Expires (Get-Date).AddYears(1)
# Issue: 1 key(s) without expiration date
# Severity: Medium
# Framework: MCSB DP-6
# Auto-remediable: False

# MANUAL REVIEW REQUIRED - key rotation schedules vary
# Example: Set 2-year expiration for encryption keys
Update-AzKeyVaultKey -VaultName 'kv-bl-pub-hzxmpoga' -Name 'WeakKey' -Expires (Get-Date).AddYears(2)

# ========================================
# Vault: kv-bl-log-hzxmpoga
# Resource Group: rg-policy-keyvault-test
# Issues: 3
# ========================================
# Issue: Purge protection is NOT enabled
# Severity: High
# Framework: CIS 8.5, MCSB DP-8
# Auto-remediable: True

Update-AzKeyVault -VaultName 'kv-bl-log-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -EnablePurgeProtection
# Issue: No firewall configured - accepts connections from all networks
# Severity: Medium
# Framework: MCSB DP-8
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - security requirements vary
# Option 1: Deny all, allow specific IPs
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-log-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -DefaultAction Deny -IpAddressRange @('1.2.3.4/32')
# Option 2: Allow Azure services bypass
Update-AzKeyVaultNetworkRuleSet -VaultName 'kv-bl-log-hzxmpoga' -ResourceGroupName 'rg-policy-keyvault-test' -Bypass AzureServices
# Issue: Diagnostic logging not configured
# Severity: Medium
# Framework: MCSB LT-3, CIS
# Auto-remediable: False

# MANUAL CONFIGURATION REQUIRED - requires Log Analytics workspace
$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName 'rg-monitoring' -Name 'law-central'
Set-AzDiagnosticSetting -ResourceId '/subscriptions/ab1336c7-687d-4107-b0f6-9649a0458adb/resourceGroups/rg-policy-keyvault-test/providers/Microsoft.KeyVault/vaults/kv-bl-log-hzxmpoga' -WorkspaceId $workspace.ResourceId -Enabled $true -Category AuditEvent

Write-Host "
Remediation complete. Review results and update compliance dashboard." -ForegroundColor Green
